AllCops:
  TargetRubyVersion: 2.5.1

  Exclude:
    - bin/**/*
    - db/migrate/*.rb
    - db/schema.rb

Rails:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/environments/*rb
    - config/routes.rb

Metrics/LineLength:
  Max: 128